garymm/build macos
EleutherAI/minetest pull request #81
Opened 2023-11-18 01:27 UTC by garymm

fix build on MacOS

- Fix zmqpp build:
  When using system zmqpp, previously the wrong variable was being set.
  When building from submodule, previously it was using make in a way that only worked if the compiler was g++. Now we use CMake which works on MacOS.

- In client: don't assume `high_resolution_clock` has `to_time_t`.

This PR is Ready for Review.

## How to test

Build the code.

2023-11-18 01:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/EleutherAI/minetest?pullRequest=81) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/EleutherAI/minetest?pullRequest=81) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/EleutherAI/minetest?pullRequest=81) it.</sub>

2023-11-28 02:33 UTC, neverix commented
The Makefile uses `util/minetester/build_minetest.sh`, which in turn uses `nproc`. I haven't finished building, but that should probably be changed

2023-11-28 20:15 UTC, garymm commented
I should clarify, I didn't get the headless support building on MacOS yet. This works with `-DBUILD_HEADLESS=FALSE`.

2023-11-28 20:46 UTC, AI-WAIFU requested changes
Can you add a check and raise an error when building for MacOS with -DBUILD_HEADLESS=TRUE? Just so fail silently/inexplicably.

2023-12-02 17:39 UTC, AI-WAIFU approved these changes
LGTM

2023-12-02 17:39 UTC, merged